### ISSUE TITLE
Error: Artifact "com.sap.sapmentors.sitregcapm.Ticket" has not been found 

### ISSUE THREAD

**Issue by matt1as** [sapmentors/sitregcapm#8]
Get the following when trying to build master, probably related to #6 not being merged correctly

```
Error: CDS compilation failed
srv\admin-service.cds:12:44-50: Error: Artifact "com.sap.sapmentors.sitregcapm.Ticket" has not been found (in entity:"AdminService.Tickets")
    at handleMessages (C:\Users\matti\Documents\Git\sitregcapm\node_modules\@sap\cds-compiler\lib\base\messages.js:119:13)
    at compileDo (C:\Users\matti\Documents\Git\sitregcapm\node_modules\@sap\cds-compiler\lib\main.js:476:3)
    at C:\Users\matti\Documents\Git\sitregcapm\node_modules\@sap\cds-compiler\lib\main.js:162:12
```

**Comment by gregorwolf** [comment]
I've merged without trying. Sorry. Can you fix it and send a pull request?

**Comment by balbinosoares** [comment]
Fixed in the new pull request...
